name: artums
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  bloc: ^8.1.3
  fluentui_system_icons: ^1.1.229
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  gap: ^3.0.1
  geolocator: ^11.0.0
  gif: ^2.3.0
  intl: ^0.19.0
  syncfusion_flutter_calendar: ^24.2.9
  syncfusion_flutter_charts: ^24.2.9
  weather: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/


  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
    #     - asset: fonts/Schyler-Italic.ttf
    #       style: italic
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700